external-libs:
  LibStub: https://repos.wowace.com/wow/libstub/trunk
  CallbackHandler-1.0: https://repos.wowace.com/wow/callbackhandler/trunk/CallbackHandler-1.0
  AceAddon-3.0: https://repos.curseforge.com/wow/ace3/trunk/AceAddon-3.0
  # AceComm-3.0: https://repos.curseforge.com/wow/ace3/trunk/AceComm-3.0
  # AceConfig-3.0: https://repos.curseforge.com/wow/ace3/trunk/AceConfig-3.0
  AceConsole-3.0: https://repos.curseforge.com/wow/ace3/trunk/AceConsole-3.0
  AceDB-3.0: https://repos.curseforge.com/wow/ace3/trunk/AceDB-3.0
  # AceDBOptions-3.0: https://repos.curseforge.com/wow/ace3/trunk/AceDBOptions-3.0
  AceEvent-3.0: https://repos.curseforge.com/wow/ace3/trunk/AceEvent-3.0
  # AceGUI-3.0: https://repos.curseforge.com/wow/ace3/trunk/AceGUI-3.0
  AceHook-3.0: https://repos.curseforge.com/wow/ace3/trunk/AceHook-3.0
  # AceLocale-3.0: https://repos.curseforge.com/wow/ace3/trunk/AceLocale-3.0
  # AceSerializer-3.0: https://repos.curseforge.com/wow/ace3/trunk/AceSerializer-3.0
  # AceTimer-3.0: https://repos.curseforge.com/wow/ace3/trunk/AceTimer-3.0

ignore:
  - config.ld
  - docs
  - libs
  - release-please-config.json