name: automerge

on:
  pull_request_target:
    types:
      - opened
      - labeled
  pull_request_review:
    types:
      - submitted
  workflow_dispatch:

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: pascalgn/automerge-action@v0.14.3
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "autorelease: pending"
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "Automatic merge of successful PR #{pullRequest.number}"
          MERGE_FORKS: "false"
          UPDATE_LABELS: "autorelease: merged"
