name: Package and Release

on:
  pull_request:
    branches:
      - master
    types:
      - closed
  workflow_dispatch:

jobs:
  post_pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Update version in .toc file
        run: |
          VERSION="v$(cat version.txt)"
          sed -i "s/## Version: .*/## Version: $VERSION/" "Ranoth's utility.toc"
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Update version in .toc file"
      - name: Push changes
        run: git push
      - name: install commands
        run: |
          sudo apt update
          sudo apt install subversion zip wget dos2unix
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.12.2/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq
      - name: Build and compress addon
        run: |
          dos2unix build.sh
          bash build.sh
      - name: Get addon name
        id: get_addon_name
        run: |
          ADDON_NAME=$(cat ./build/addonName.txt)
          echo "::set-output name=addonname::$ADDON_NAME"
      - name: Get latest release
        id: get_release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_URL=$(gh api repos/:owner/:repo/releases/latest --jq .upload_url)
          echo "RELEASE_URL=$RELEASE_URL" >> $GITHUB_ENV
      - name: Attach built addon to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.RELEASE_URL }}
          asset_path: ./build/${{ steps.get_addon_name.outputs.addonname }}.zip
          asset_name: ${{ steps.get_addon_name.outputs.addonname }}.zip
          asset_content_type: application/zip
      - name: Get release body
        id: get_release_body
        run: |
          RELEASE_JSON=$(curl --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }}")
          RELEASE_BODY=$(echo $RELEASE_JSON | jq -r .body | sed ':a;N;$!ba;s/\n/\\n/g')
          echo "::set-output name=release_body::$RELEASE_BODY"

      - name: Upload to CurseForge
        uses: itsmeow/curseforge-upload@v3
        with:
          file_path: "./build/${{ steps.get_addon_name.outputs.addonname }}.zip"
          game_endpoint: "wow"
          project_id: "1000615"
          token: ${{ secrets.CF_API_KEY }}
          changelog: ${{ steps.get_release_body.outputs.release_body }}
          changelog_type: "markdown"
          game_versions: "10.2.7"
