name: LDoc
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
    ldoc:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Generate docs with LDoc
              uses: lunarmodules/ldoc@v1
              with:
                args: ./*.lua
