name: LDoc
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  ldoc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Lua
        uses: leafo/gh-actions-lua@v8
        with:
          luaVersion: "5.1"

      - name: Setup LDoc
        run: |
          sudo luarocks install ldoc

      - name: Generate docs with LDoc
        run: |
          ldoc ./*.lua -o ./docs
