name: release-please
on:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
  automerge:
    needs: release-please
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: pascalgn/automerge-action@v0.14.3
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: "autorelease: pending"
          MERGE_METHOD: "merge"
          MERGE_COMMIT_MESSAGE: "Automatic merge of successful PR #{pullRequest.number}"
          MERGE_FORKS: "false"
          UPDATE_LABELS: "autorelease: merged"
