name: release-please
on:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
  automerge:
    needs: release-please
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Merge PR
        run: |
          PR_NUMBER=$(gh pr list --label "autorelease: pending" --json number -q '.[0].number')
          if [ -n "$PR_NUMBER" ]; then
            git fetch origin pull/$PR_NUMBER/head:pr-$PR_NUMBER
            git checkout master
            git merge --no-ff pr-$PR_NUMBER
            git fetch --tags
            git push origin master --tags
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
