name: auto pr
on:
  push:
    branches:
      - master

jobs:
  make-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: release
        uses: google-github-actions/release-please-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
